language: php
php:
    - '7.1'
    - '7.2'
    - '7.3'

before_script: composer install
script:
    - vendor/bin/phpunit --color -c phpunit.xml.dist

after_success:
    - travis_retry php vendor/bin/php-coveralls